{% set version = '0.9-107' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-logging
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/logging_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/logging/logging_{{ version }}.tar.gz
  sha256: b7194178d1e29bee6f8673bc5b6073bfd334707457563f3c96df580cb2226f62

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, crayon
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('logging')"           # [not win]
    - "\"%R%\" -e \"library('logging')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/WLOGSolutions/r-logging
  license: GPL-3
  summary: Pure R implementation of the ubiquitous log4j package. It offers hierarchic  loggers,
    multiple handlers per logger, level based filtering, space handling in messages  and
    custom formatting.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: logging
# Version: 0.9-107
# Title: R Logging Package
# Authors@R: c( person("Mario", "Frasca", email = "mariotomo@gmail.com", role = c("aut")), person("Walerian", "Sokolowski", email = "r-logging@wlogsolutions.com", role = c("cre")) )
# Description: Pure R implementation of the ubiquitous log4j package. It offers hierarchic  loggers, multiple handlers per logger, level based filtering, space handling in messages  and custom formatting.
# URL: https://github.com/WLOGSolutions/r-logging
# BugReports: https://github.com/WLOGSolutions/r-logging/issues
# License: GPL-3
# Encoding: UTF-8
# Language: en-US
# Depends: R (>= 3.2.0)
# Imports: methods
# Suggests: testthat, crayon
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-02-10 10:59:02 UTC; ws171913
# Author: Mario Frasca [aut], Walerian Sokolowski [cre]
# Maintainer: Walerian Sokolowski <r-logging@wlogsolutions.com>
# Repository: CRAN
# Date/Publication: 2019-02-10 11:40:02 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
