travis:
  secure:
    BINSTAR_TOKEN: h9D1ceLldrLwj64N95AcqibB5FHn70+mmZUlgDobW7h2w8PqDEkp8zqXx2bDDpioPYew86JWZ+jqXyyjzOP96UXAmTqpS0ydGVwFVRTjWPwOIqx7hwhjjbD3coNZ7z+4nyQyKkmhFMlhm//OLvRqkQLO1GAeESeaSNvrV6ukkw2ChIKc4bwgz5usrquQzpzRBxc6ZC63UpXkchd117Sx4jAHNpv2TEJjv+lB0vDRebsoyu8YwUQGaibsg4B0MzL0NI9NbyKohSzJsPDEXpB7P4DkElWbfwnIE4AAX+0puYlyaIqt9/1swXWZ+YzTyR1TlRko7sPmdd84o2kGFDi4mZYq1/xqMTXrqPQmGXxoNBi/9YqKZKI3rqdh0VZCrfklharUdG/fDZ1cfTwfTtJ/FLXB46eQG3Do4o8EAvdwVnopifDmIggJdauwPMefSVAILrT1V4cJjO9+nxVIp2HAvewJM/TTy8yhrgZwoiDCToGXDITRc6ANzdDztXL4QL2wzhy/QPY9ZOQboACNPcCG5ZOIs79sgte+3YnkizjGvU2gWuEsCku0hWyIetFQLMWfBAqHkKA+LMKeIf/v0mNkHtEps0zP4CRazFaWQ9mgbE6m+sW1GuIvFV7Um4HdjXuL+pvEYaYbqQlzSm0mbdT/22tEbZM9GUGggvdVnSAebKE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
