travis:
  secure:
    BINSTAR_TOKEN: uoTkKt1MPa0m5sm0per2m2EbIugs8pFxP82KZ9d+CMr+rROyaL6pYQEa2mnewmWugm5ecsT/DNZq7gOBpMIqWD6RpipliE70oyrNjrV/u7LtmM3QQ725OYOQfq80yUhtpFTYUrE1MxS/0XwcEhRDRtp8v5V47cM+Mnp3E4/rM1HHjQUbK253sL6Bug8QV444rsJ/CBcXThLebbeOoIDjRlAjInhEUhDWAXwCM7GjcQQTGO7E+ghp2s4iDbcBwu2YhWeo8uXG6rCpv7vp0VxHbAwRS7PW4R4I4nbBRUi3TEPAHM/C5v6dyjuc9Aq1Dn662/hurvZggF0xuagY25iZuKFXuzsHhUBUkP/gGimB+tvejkGG+G/VJIAABN4Dzyy1lRV0fPP8PNbVenM+1dFZwaT2EnJhrr/uJR4WngmxqGQnZvmnF4Mb6v8YWlXCWOL4JeiHErNyGWwNddx2RvfdaQaM67zqLu6BiONevIDYCtil5F4c4hTSFZAIXb2VG5eTbJMyYhkOzZR0XB7LlRzJD//diT7nwdojG6BPxXOzmcL4XCtrjXhn8T8IIupDtAG3xkynIq+kaaePZbSjhMbcY3lhz7a5cab7QLhnVPRVxnocdGc6pmGG2/ve6PMu3dweFzBeBmoqNuMjvEx0ddxjnbK2wDY7VisrDks0kgDtmMg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
